### ISSUE TITLE
ValueError: root found before file_input node was found. 

### ISSUE THREAD

**Issue by myint** [liamcurry/py3kwarn#2]
I'm getting a `ValueError` exception when running `py3kwarn` and when running the test cases.

``` bash
$ python --version
Python 3.3.1
$ make test
python -m py3kwarn.tests
.....EEEE.EE..
======================================================================
ERROR: test_except (__main__.TestPy3kWarn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./py3kwarn/tests.py", line 66, in test_except
    self._test_code('except')
  File "./py3kwarn/tests.py", line 43, in _test_code
    warnings = warnings_for_string(globals()['code_' + name], name)
  File "./py3kwarn/run.py", line 115, in warnings_for_string
    tree = _rt.refactor_string(data, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/lib2to3/refactor.py", line 386, in refactor_string
    self.refactor_tree(tree, name)
  File "./py3kwarn/run.py", line 70, in refactor_tree
    find_root(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/lib2to3/fixer_util.py", line 279, in find_root
    raise ValueError("root found before file_input node was found.")
ValueError: root found before file_input node was found.
.
.
.
```

It does work on Python 2.7 though.

By the way, since you are already using setuptools, you may want to enable tests in your `setup.py`. It allows for the fairly standard `python setup.py test` command.

``` diff
diff --git a/setup.py b/setup.py
index 04dd51e..ccd3443 100755
--- a/setup.py
+++ b/setup.py
@@ -32,4 +32,5 @@ setup(name='py3kwarn',
           'Programming Language :: Python',
           'Topic :: Software Development',
           'Topic :: Utilities',
-      ])
+      ],
+      test_suite='py3kwarn.tests')
```

**Comment by liamcurry** [comment]
Thanks for the suggestion -- I made that change and added your name to the contributors list.

I'll need a little time to see what's causing the problems in 3.3.1.

**Comment by liamcurry** [comment]
Per #3, I think for now we should only support 2.6/2.7, since many of these warnings will be syntax errors in Python 3 anyway.
